services:
  pgdatabase:
    image: postgres:13
    env_file:
        - .env
    volumes:
      - "./sponsorblock_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - airflow

networks:
  airflow:
    external:
      name: airflow_default